<?php
$aMenuLinks = Array(
    Array(
        "Главная", 
        "/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Каталог товаров", 
        "/products/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Оплата",
        "/oplata/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Доставка",
        "/delivery/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Договор оферты",
        "/dogovor-oferti/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "FAQ",
        "/faq/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "/contacts/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Ремонт моторов",
        "/remont_motorov/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Выкуп мототехники",
        "/vikup_mototehniki/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Сотрудничество",
        "/sotrudnichestvo/",
        Array(),
        Array(),
        ""
    )
);
?>

